# Generated by Django 5.1 on 2025-01-21 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('departments', '0001_initial'),
        ('patron', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('patron_fname', models.CharField(max_length=100)),
                ('patron_lname', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('patron_type', models.CharField(max_length=50)),
                ('request_status', models.CharField(max_length=20)),
                ('patron_due_date', models.DateField(blank=True, null=True)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patron.patron')),
                ('patron_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('request_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
