# Generated by Django 5.1 on 2025-01-21 05:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('book_borrowing_period', models.IntegerField(blank=True, null=True)),
                ('patron_id_number', models.CharField(max_length=100)),
                ('patron_id', models.AutoField(primary_key=True, serialize=False)),
                ('patron_type', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Employee', 'Employee')], default='Student', max_length=50)),
                ('patron_fname', models.CharField(max_length=100)),
                ('patron_lname', models.CharField(max_length=100)),
                ('patron_email', models.EmailField(max_length=254)),
                ('patron_contact_no', models.CharField(max_length=15)),
                ('date_added', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('patron_approved_date', models.DateField(blank=True, null=True)),
                ('request_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Overdue', 'Overdue'), ('Returned', 'Returned')], default='Pending', max_length=20)),
                ('patron_due_date', models.DateField(blank=True, null=True)),
                ('overdue_days', models.IntegerField(default=0)),
                ('patron_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('request_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book')),
            ],
        ),
    ]
