# Generated by Django 5.1 on 2025-01-21 05:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('profile_image', models.TextField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
