# Generated by Django 5.1 on 2025-01-21 05:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=200)),
                ('book_isbn', models.CharField(max_length=13, unique=True)),
                ('book_author', models.CharField(max_length=100)),
                ('book_total_copies', models.IntegerField()),
                ('book_available_copies', models.IntegerField()),
                ('book_desc', models.TextField()),
                ('book_image', models.TextField()),
                ('borrowing_period', models.IntegerField(default=7)),
                ('book_date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
